name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9","3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run Tests
      run: |
        cd src
        pytest addition.py
